#-----------------------------------------------------------------------------------------------------------------------
# Minnaker recipe
#
# Self contained Spinnaker installation with no external dependencies and no additional configuration needed.
# Not for production use.
#
# Features:
# - One Kubernetes account (Spinnaker's own cluster) for deployment targets
# - One dockerhub account for public repositories
# - One HTTP account enabled
# - Spinnaker configured to use the same host for Deck and Gate
# - Spinnaker Basic Auth enabled
# - Spinnaker exposed via Traefik
# - Self hosted minio as a persistent storage
# - Self hosted redis backend for caching and temporal storage of services
#-----------------------------------------------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker

resources:
  - expose/ingress-traefik.yml              # Use Traefik for Ingress

components:
  - core/base
  - core/persistence/in-cluster
  - targets/kubernetes/default

patchesStrategicMerge:
  - core/patches/version.yml
  - expose/patch-ingress.yml                # Automatically expose spinnaker
  - security/patch-basic-auth.yml           # Enable Basic Auth
  - security/patch-gate-tomcat-headers.yml  # Add headers to Tomcat for Gate
  - accounts/docker/patch-dockerhub.yml     # Docker accounts
  - accounts/http/patch-http.yml            # HTTP accounts
