apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - provider.yml

secretGenerator:
  - name: pcf-secret
    options:
      disableNameSuffixHash: true
    literals:
      - cf-password=SampleAccessKey1!
